// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "TitleCard":return img`
....................................................................................................
....................................................................................................
....................................................................................................
.......fffffffff.......fffffff......................................................................
.....ffcccccccccf.....fccccccffff...................................................................
...ffccccccccccccf....fcccccccccfff.................................................................
..ffccccfffffcccccf...fcccccccccccff................................................................
..fcccff.....ffcccf...fccccccccccccff...............................................................
.fcccff.......fcccf...fcccccccccccccf...............................................................
.fccff........fcccf...fcccfffcccccccff..............................................................
.fccf.........fcccf...fcccf..ffccccccf..............................................................
.ffff.........fcccf...fcccf....fcccccf..............................................................
.............ffccff...fcccf....ffccccf..............................................................
............ffcccf....fcccf.....fccccf..............................................................
..........fffcccf.....fcccf......fcccf.fff.ffff.....................................................
.........ffccccf......fcccf......fcccf.fbffbbbf...ffff......ffffff....fff.ff.....fff................
........ffccccccff....fcccf......fcccf.fbbbbbbf.fffbbfff...ffbbbbff...fbffbbff..fbbf................
........fcccccccccff..fcccf......fcccf.fbbbfff..fbbbbbbff..fbbbbbbf...fbfbbbbfffbbbbf...............
........ffffffcccccff.fcccf......fcccf.fbbf....fbbbffbbbf.ffbbbbbbf...fbbbbbbbfbbbbbf...............
.............ffcccccf.fcccf.....fccccf.fbf....ffbbf..fbbf.fbbbffbbf...fbbbffbbbbbffbf...............
..............ffccccf.fcccf.....fccccf.fbf....fbbf....fbf.fbbf.fbbf...fbbff.fbbbf.fbf...............
...............fccccf.fcccf....fcccccf.fbf....fbbffffffbf.fbf..fbbff..fbff...fbf..fbf...............
..............ffccccf.fcccf..fffccccf..fbf....fbbbbbbbbbf.fbf..fbbbf..fbf....fbf..fbf...............
....fffffffffffcccccf.fcccfffcccccccf..fbf....fbbfffffff..fbbf.fbbbf..fbf.....f...fbf...............
...fcccccccccccccccf..fccccccccccccff..fbf....fbf.........fbbbfbbbbbf.fbf.........fbf...............
...fccccccccccccccf...fccccccccccccf...fbf....fbbfffffff..fbbbbbffbbf.fbf.........fbf...............
...fcccccccccccccff...ffcccccccccff....fbf....ffbbbbbbbbf.ffbbbbfffbf.fbf.........fbf...............
....fffffffffffff......fffffffffff.....fff......fffffffff..ffffff.fff.fff.........fff...............
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
